### ISSUE TITLE
Missing quotes in yaml output 

### ISSUE THREAD

**Issue by jayvdb** [podhmo/jqfpy#24]
I tried to round-trip a `pnpm` `shrinkwrap.yaml`, and found that it drops quotes around strings containing `#`, which in this example are npm's silly use of `#` to indicate branch (which `pnpm` also uses)

```diff
@@ -6082,7 +6088,7 @@
   '@ionic-native/splash-screen': 4.4.0
   '@ionic-native/status-bar': 4.4.0
   '@ionic-native/transfer': ^3.14.0
-  '@ionic/app-scripts': 'github:jayvdb/ionic-app-scripts#fix-path-strategy-deploy'
+  '@ionic/app-scripts': github:jayvdb/ionic-app-scripts#fix-path-strategy-deploy
   '@ionic/storage': ^2.1.3
   '@types/jasmine': 2.8.9
   '@types/netlify-identity-widget': ^1.4.0
@@ -6107,7 +6113,7 @@
   http-server-spa: 1.3.0
   ionic-angular: 3.9.2
   ionic-cache: ^2.1.0
-  ionic-img-viewer: 'git+https://github.com/blazeu/ionic-img-viewer.git#image-content'
+  ionic-img-viewer: git+https://github.com/blazeu/ionic-img-viewer.git#image-content
   ionic-native: ^2.9.0
   ionic-plugin-keyboard: ^2.2.1
   ionicons: 3.0.0
```

**Comment by jayvdb** [comment]
Ahh turns out a space is needed before `#` for it to be a comment.  That serves me right for raising an issue at 4 am ;)

Anyways, it would be nice to retain style of the input.  Using `raumel.yaml`'s round tripper, if available, will help with that.

**Comment by podhmo** [comment]
ok, thanks, I'll check ruamel.yaml

**Comment by podhmo** [comment]
Anyway, If it is existed something like ‘--must-quoted‘ option, solving your problem?

**Comment by jayvdb** [comment]
The option would be '--quotes-around-hash'

**Comment by podhmo** [comment]
currently, always quoted
